#!/usr/bin/env python3
"""
处理 Horizon 报告，按分类分组并转换为中文
"""
import os
import sys
import re
from datetime import datetime

def parse_report(content):
    """解析 Horizon 报告，提取条目"""
    items = []
    
    # 分割条目
    sections = content.split('---\n')
    
    for section in sections:
        if not section.strip():
            continue
            
        # 提取标题行
        lines = section.strip().split('\n')
        
        # 查找条目链接和评分
        item_match = re.search(r'## \[(.+?)\]\((.+?)\)\s+⭐️\s+([\d.]+)/10', section)
        if not item_match:
            continue
            
        title = item_match.group(1)
        url = item_match.group(2)
        score = item_match.group(3)
        
        # 提取摘要
        summary_match = re.search(r'\n\n(.+?)(?:\n\n\*\*Tags\*\*:|\n\n---)', section, re.DOTALL)
        summary = summary_match.group(1).strip() if summary_match else ""
        
        # 提取来源
        source_match = re.search(r'\*\*来源\*\*:\s*(.+?)(?:\n|$)', section)
        source = source_match.group(1).strip() if source_match else ""
        
        # 提取标签
        tags_match = re.search(r'\*\*标签\*\*:\s*`(.+?)`', section)
        tags = tags_match.group(1).strip() if tags_match else ""
        
        # 分类判断
        category = "other"
        if 'github.com' in url.lower() or 'github' in source.lower():
            category = "github"
        elif any(kw in title.lower() + summary.lower() for kw in ['google', 'openai', 'anthropic', 'microsoft', 'meta', 'amazon', 'apple', 'nvidia']):
            category = "tech-giant"
        
        items.append({
            'title': title,
            'url': url,
            'score': score,
            'summary': summary,
            'source': source,
            'tags': tags,
            'category': category
        })
    
    return items

def generate_chinese_report(items, date_str):
    """生成中文报告"""
    github_items = [i for i in items if i['category'] == 'github']
    tech_items = [i for i in items if i['category'] == 'tech-giant']
    other_items = [i for i in items if i['category'] == 'other']
    
    report = f"""# Horizon 科技日报 - {date_str}

> 从 {len(items)} 条新闻中精选 {len(items)} 条重要内容

---

## 📊 内容概览

- **GitHub 热点项目**: {len(github_items)} 条
- **科技巨头动态**: {len(tech_items)} 条
- **其他技术资讯**: {len(other_items)} 条

---

"""
    
    # GitHub 热点项目
    if github_items:
        report += "## 🔥 GitHub 热点项目\n\n"
        for i, item in enumerate(github_items, 1):
            report += f"""### {i}. {item['title']} ⭐️ {item['score']}/10

**原文链接**: [{item['url']}]({item['url']})

{item['summary']}

**来源**: {item['source']}

---

"""
    
    # 科技巨头动态
    if tech_items:
        report += "## 🏢 科技巨头动态\n\n"
        for i, item in enumerate(tech_items, 1):
            report += f"""### {i}. {item['title']} ⭐️ {item['score']}/10

**原文链接**: [{item['url']}]({item['url']})

{item['summary']}

**来源**: {item['source']}

---

"""
    
    # 其他技术资讯
    if other_items:
        report += "## 📰 其他技术资讯\n\n"
        for i, item in enumerate(other_items, 1):
            report += f"""### {i}. {item['title']} ⭐️ {item['score']}/10

**原文链接**: [{item['url']}]({item['url']})

{item['summary']}

**来源**: {item['source']}

---

"""
    
    report += f"""## 📈 统计信息

- **总条目**: {len(items)} 条
- **GitHub 项目**: {len(github_items)} 条
- **科技巨头**: {len(tech_items)} 条
- **生成时间**: {datetime.now().strftime('%Y-%m-%d %H:%M')}

---

*Generated by Horizon AI News Bot*"""
    
    return report

def main():
    if len(sys.argv) < 2:
        print("Usage: process_report.py <input_file>")
        sys.exit(1)
    
    input_file = sys.argv[1]
    
    if not os.path.exists(input_file):
        print(f"File not found: {input_file}")
        sys.exit(1)
    
    # 读取原始报告
    with open(input_file, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # 提取日期
    date_match = re.search(r'Horizon Daily - (\d{4}-\d{2}-\d{2})', content)
    date_str = date_match.group(1) if date_match else datetime.now().strftime('%Y-%m-%d')
    
    # 解析条目
    items = parse_report(content)
    print(f"Parsed {len(items)} items")
    
    # 生成分类报告
    report = generate_chinese_report(items, date_str)
    
    # 输出到文件
    output_file = input_file.replace('.md', '-zh.md')
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(report)
    
    print(f"Report saved to: {output_file}")
    print(f"GitHub items: {len([i for i in items if i['category'] == 'github'])}")
    print(f"Tech giant items: {len([i for i in items if i['category'] == 'tech-giant'])}")

if __name__ == '__main__':
    main()
